#!/usr/bin/env bash
# Author: Rafael Kaissi <mrkaissi@gmail.com>

is_root() {
  if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "false"
  else
    echo "true"
  fi
}

must_be_root() {
  if [ `is_root` = "false" ]; then
    echo "Not running as root"
    exit 1
  fi
}
